## ARCHIVO UTILIZADO PARA LA EJECUCION DEL DOCKER COMPOSE 
version: "3.8"
## El archivo no fue alterado, las versiones usadas en el tutorial fueron dejadas 
## Las variables de entorno no sufrieron ningun cambio al considerarse que no era tan relevante la modificacion de estas 
services:
  mysqldb:
    image: mysql:5.7
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    logging:
      driver: none
## NOTA EXTRA: MI COMPUTADORA ME MARCA ERROR AL USAR EL PUERTO 8080 POR ESO SIEMPRE TENGO QUE CAMBIAR EL ULTIMO NUMERO PARA QUE ME PUEDA CORRER EL CONTENEDOR
  app:
    depends_on:
      - mysqldb
    links:
      - mysqldb
    build: .
    # restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT

